### ISSUE TITLE
mdnotes-generates pages have bad yaml

### ISSUE THREAD

**Issue by pskyhx** [ragynotes/ragynotes.github.io#25]
attempting to build

```sh
Error: Error building site: ".../ragynotes.github.io/content/testing/Nov22/document-1912botanicalsurveyofindia-mdn.md:3:1": failed to unmarshal YAML: yaml: line 2: mapping values are not allowed in this context
```

**Comment by pskyhx** [comment]
this in the template:

```yaml
tags:								# ⚠️ check how does this output
	- {{tags}}
#summary: 							# ❗
```

produces this: 

```yaml
tags:								# ⚠️ check how does this output
	- #summary: 							# ❗
```

because there are no tags.

**Comment by pskyhx** [comment]
There is a colon in the title which breaks the YAML:

> failed to unmarshal YAML: yaml: mapping values are not allowed in this context

Enclosing it in quotes seems to fix.

**Comment by pskyhx** [comment]
Problem: when values are missing

```yaml
---
title: "{{title}}"
title-short: "{{shortTitle}}"
originalyear: {{date}}
type: "{{itemType}}"

alias: "{{citekey}}"
lang: "{{language}}"

draft: true

date: {{accessDate}}
---
```

becomes in a files with minimal metadata:

```yaml
---
title: "ZZZZ test fake file"
title-short: ""
originalyear: type: ""

alias: "zotero-1405"
lang: ""

draft: true

date: ---
```

Problems:
1. missing `originalyear` squashes next line into it
2. end of `yaml` `---` is not on own line. 

solution to both: trailing space at end of line after `}}` retains the structure. Is trailing space in violation of `yaml`? If that ended up being the case, could solve similarly to `tags` above by re-integrating the whole line into the `mdnotes` output. for now it looks fine. 

All my test files can now pass through `mdnotes` batch export without breaking hugo. :)
